[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.22"
image = "0.24.8"
mozjpeg = "0.10.6"
anyhow = "1.0.79"